export interface TeamMember {
  id: string;
  name: string;
  title: string;
  department: string;
  role: "Lead" | "Co-Lead" | "Core Member" | "Founder" | "Placeholder";
  registrationNumber?: string;
  email?: string;
  phone?: string;
  image: string;
  tags: string[];
  bio: string;
  stats?: {
    yearsInPractice?: number;
    rating?: number;
    projects?: number;
  };
  socials?: {
    linkedin?: string;
    github?: string;
    email?: string;
  };
  isPlaceholder?: boolean;
}

export const departments = [
  "All",
  "Developer Team",
  "Tech Team",
  "Design Team",
  "Social Media",
  "Event Management",
  "PR Team",
  "Research Team",
  "Founders",
] as const;

export type DepartmentType = (typeof departments)[number];

export const teamMembers: TeamMember[] = [
  // --- DEVELOPER TEAM ---
  {
    id: "dev-1",
    name: "Mangal Singh",
    title: "Developer Team Lead",
    department: "Developer Team",
    role: "Lead",
    registrationNumber: "24BCE10599",
    email: "mangal.24bce10599@vitbhopal.ac.in",
    phone: "8974256208",
    image: "/team/mangal-singh.jpg",
    tags: ["LEAD", "FULLSTACK", "TECH ARCHITECTURE"],
    bio: "Lead of Developer Team at QIC. Driving technical initiatives, robust system architecture, and steering club development projects.",
    stats: {
      yearsInPractice: 2,
      rating: 4.9,
      projects: 12,
    },
    socials: {
      email: "mangal.24bce10599@vitbhopal.ac.in",
    },
  },
  {
    id: "dev-2",
    name: "Mausam Kar",
    title: "Developer Team Co-Lead",
    department: "Developer Team",
    role: "Co-Lead",
    registrationNumber: "24BAI10284",
    email: "mausam.24bai10284@vitbhopal.ac.in",
    phone: "8638545574",
    image: "",
    tags: ["CO-LEAD", "AI/ML", "SOFTWARE ENG"],
    bio: "Co-Lead of Developer Team at QIC. Specializing in AI/ML solutions, intelligent pipelines, and collaborative software development.",
    stats: {
      yearsInPractice: 2,
      rating: 4.8,
      projects: 10,
    },
    socials: {
      email: "mausam.24bai10284@vitbhopal.ac.in",
    },
  },
  {
    id: "dev-3",
    name: "Jaydeep",
    title: "Core Developer",
    department: "Developer Team",
    role: "Core Member",
    registrationNumber: "24BCE10280",
    email: "jaydeep.24bce10280@vitbhopal.ac.in",
    phone: "9892154631",
    image: "",
    tags: ["DEVELOPER", "FRONTEND", "UI/UX"],
    bio: "Core developer contributing to responsive user interfaces, interactive web components, and frontend stability.",
    stats: {
      yearsInPractice: 1,
      rating: 4.7,
      projects: 6,
    },
    socials: {
      email: "jaydeep.24bce10280@vitbhopal.ac.in",
    },
  },
  {
    id: "dev-4",
    name: "Bhavishya Gupta",
    title: "Core Developer",
    department: "Developer Team",
    role: "Core Member",
    registrationNumber: "25BCE10588",
    email: "bhavishya.25bce10588@vitbhopal.ac.in",
    phone: "8707399551",
    image: "",
    tags: ["DEVELOPER", "WEB DEV", "JAVASCRIPT"],
    bio: "Core developer crafting clean modern web interfaces and implementing performant modular components.",
    stats: {
      yearsInPractice: 1,
      rating: 4.8,
      projects: 5,
    },
    socials: {
      email: "bhavishya.25bce10588@vitbhopal.ac.in",
    },
  },
  {
    id: "dev-5",
    name: "Aditi Sahu",
    title: "Core Developer",
    department: "Developer Team",
    role: "Core Member",
    registrationNumber: "25BCE10844",
    email: "aditi.25bce10844@vitbhopal.ac.in",
    phone: "8756782460",
    image: "",
    tags: ["DEVELOPER", "BACKEND", "API SERVICES"],
    bio: "Core developer engineering backend services, REST APIs, and database integrations for club projects.",
    stats: {
      yearsInPractice: 1,
      rating: 4.7,
      projects: 6,
    },
    socials: {
      email: "aditi.25bce10844@vitbhopal.ac.in",
    },
  },
  {
    id: "dev-6",
    name: "Zinnia Kar",
    title: "Core Developer",
    department: "Developer Team",
    role: "Core Member",
    registrationNumber: "24BCY10089",
    email: "zinnia.24bcy10089@vitbhopal.ac.in",
    phone: "8073856323",
    image: "",
    tags: ["DEVELOPER", "CYBERSECURITY", "SECURITY"],
    bio: "Core developer focusing on secure software development, vulnerability assessment, and platform hardening.",
    stats: {
      yearsInPractice: 2,
      rating: 4.8,
      projects: 7,
    },
    socials: {
      email: "zinnia.24bcy10089@vitbhopal.ac.in",
    },
  },
  {
    id: "dev-7",
    name: "Shivansh Kadam",
    title: "Core Developer",
    department: "Developer Team",
    role: "Core Member",
    registrationNumber: "25MIP10070",
    email: "kadam.25mip10070@vitbhopal.ac.in",
    phone: "8805947742",
    image: "",
    tags: ["DEVELOPER", "SYSTEMS", "FULLSTACK"],
    bio: "Core developer building integrated software solutions, developer utilities, and reliable systems.",
    stats: {
      yearsInPractice: 1,
      rating: 4.6,
      projects: 5,
    },
    socials: {
      email: "kadam.25mip10070@vitbhopal.ac.in",
    },
  },
  {
    id: "dev-8",
    name: "Sudarsh Karan Chauhan",
    title: "Core Developer",
    department: "Developer Team",
    role: "Core Member",
    registrationNumber: "24BCE10057",
    email: "sudarsh.24bce10057@vitbhopal.ac.in",
    phone: "8000973364",
    image: "",
    tags: ["DEVELOPER", "WEB", "MODERN JS"],
    bio: "Core developer designing accessible web applications, responsive layouts, and club portals.",
    stats: {
      yearsInPractice: 2,
      rating: 4.7,
      projects: 6,
    },
    socials: {
      email: "sudarsh.24bce10057@vitbhopal.ac.in",
    },
  },
  {
    id: "dev-9",
    name: "Harshul Agarwal",
    title: "Core Developer",
    department: "Developer Team",
    role: "Core Member",
    registrationNumber: "25BCE11080",
    email: "harshul.25bce11080@vitbhopal.ac.in",
    phone: "6201737081",
    image: "",
    tags: ["DEVELOPER", "ALGORITHMS", "OPTIMIZATION"],
    bio: "Core developer with a deep passion for algorithmic problem solving, code optimization, and platform tooling.",
    stats: {
      yearsInPractice: 1,
      rating: 4.7,
      projects: 5,
    },
    socials: {
      email: "harshul.25bce11080@vitbhopal.ac.in",
    },
  },
  {
    id: "dev-10",
    name: "Shubham Awasthi",
    title: "Core Developer",
    department: "Developer Team",
    role: "Core Member",
    registrationNumber: "24BCE11054",
    email: "shubham.24bce11054@vitbhopal.ac.in",
    phone: "7009318067",
    image: "",
    tags: ["DEVELOPER", "SOFTWARE", "APPLICATIONS"],
    bio: "Core developer contributing to high quality software architecture, digital features, and team codebases.",
    stats: {
      yearsInPractice: 2,
      rating: 4.7,
      projects: 7,
    },
    socials: {
      email: "shubham.24bce11054@vitbhopal.ac.in",
    },
  },
  {
    id: "dev-11",
    name: "Arunima Singh",
    title: "Core Developer",
    department: "Developer Team",
    role: "Core Member",
    registrationNumber: "24BAI10143",
    email: "arunima.24bai10143@vitbhopal.ac.in",
    phone: "9301992183",
    image: "",
    tags: ["DEVELOPER", "AI", "INTELLIGENT SYSTEMS"],
    bio: "Core developer exploring machine learning integrations, data processing, and smart club software.",
    stats: {
      yearsInPractice: 2,
      rating: 4.8,
      projects: 6,
    },
    socials: {
      email: "arunima.24bai10143@vitbhopal.ac.in",
    },
  },
  {
    id: "dev-12",
    name: "Rajshekhar",
    title: "Core Developer",
    department: "Developer Team",
    role: "Core Member",
    registrationNumber: "24BAI10728",
    email: "rajshekhar.24bai10728@vitbhopal.ac.in",
    phone: "9068317281",
    image: "",
    tags: ["DEVELOPER", "COMPUTING", "DATA STRUCTURES"],
    bio: "Core developer focused on computational logic, resilient system code, and software development.",
    stats: {
      yearsInPractice: 2,
      rating: 4.7,
      projects: 5,
    },
    socials: {
      email: "rajshekhar.24bai10728@vitbhopal.ac.in",
    },
  },
  {
    id: "dev-13",
    name: "Rohan Sinha",
    title: "Core Developer",
    department: "Developer Team",
    role: "Core Member",
    registrationNumber: "25BAI10714",
    email: "rohan.25bai10714@vitbhopal.ac.in",
    phone: "7004229132",
    image: "",
    tags: ["DEVELOPER", "DATA SCIENCE", "AI APPLICATIONS"],
    bio: "Core developer building data workflows, analytical models, and modern software utilities.",
    stats: {
      yearsInPractice: 1,
      rating: 4.6,
      projects: 4,
    },
    socials: {
      email: "rohan.25bai10714@vitbhopal.ac.in",
    },
  },

  
  // --- TECH TEAM (TEMPLATE) ---
  {
    id: "tech-1",
    name: "Tech Lead",
    title: "Tech Team Lead",
    department: "Tech Team",
    role: "Lead",
    image: "",
    tags: ["LEAD", "TECH", "INFRASTRUCTURE"],
    bio: "Position Open / TBA. Leading technical vision, system architecture, and technical workshops for QIC.",
    isPlaceholder: true,
    stats: { yearsInPractice: 2, rating: 4.8, projects: 10 },
  },
  {
    id: "tech-2",
    name: "Tech Co-Lead",
    title: "Tech Team Co-Lead",
    department: "Tech Team",
    role: "Co-Lead",
    image: "",
    tags: ["CO-LEAD", "SYSTEMS", "ENGINEERING"],
    bio: "Position Open / TBA. Co-leading technical operations, hands-on labs, and infrastructure.",
    isPlaceholder: true,
    stats: { yearsInPractice: 1, rating: 4.7, projects: 7 },
  },
  {
    id: "tech-3",
    name: "Tech Core Member",
    title: "Tech Core Member",
    department: "Tech Team",
    role: "Core Member",
    image: "",
    tags: ["CORE", "TECHNICAL", "SYSTEMS"],
    bio: "Position Open / TBA. Supporting technical setups, lab hardware, and platform operations.",
    isPlaceholder: true,
    stats: { yearsInPractice: 1, rating: 4.6, projects: 5 },
  },
// --- DESIGN TEAM (DESIGN TEAM QIC) ---
  {
    id: "des-1",
    name: "Yash Kumavat",
    title: "Design Team Lead",
    department: "Design Team",
    role: "Lead",
    registrationNumber: "24BSA10098",
    email: "yash.24bsa@vitbhopal.ac.in",
    phone: "9867330059",
    image: "",
    tags: ["LEAD", "DESIGN", "CREATIVE DIRECTION"],
    bio: "Lead of Design Team at QIC. Directing visual branding, creative assets, UI/UX identity, and design guidelines.",
    stats: {
      yearsInPractice: 2,
      rating: 4.9,
      projects: 15,
    },
    socials: {
      email: "yash.24bsa@vitbhopal.ac.in",
    },
  },
  {
    id: "des-2",
    name: "Design Co-Lead",
    title: "Design Team Co-Lead",
    department: "Design Team",
    role: "Co-Lead",
    image: "",
    tags: ["CO-LEAD", "UI/UX", "CREATIVE"],
    bio: "Position Open / TBA. Co-leading creative workflows, UI/UX prototypes, and design asset production.",
    isPlaceholder: true,
    stats: {
      yearsInPractice: 1,
      rating: 4.8,
      projects: 8,
    },
  },
  {
    id: "des-3",
    name: "Design Core Member",
    title: "Design Core Member",
    department: "Design Team",
    role: "Core Member",
    image: "",
    tags: ["CORE", "GRAPHICS", "BRANDING"],
    bio: "Position Open / TBA. Crafting digital banners, vector illustrations, and brand visual assets.",
    isPlaceholder: true,
    stats: {
      yearsInPractice: 1,
      rating: 4.7,
      projects: 5,
    },
  },

  // --- SOCIAL MEDIA TEAM ---
  {
    id: "sm-1",
    name: "Yash Kumavat",
    title: "Social Media Lead",
    department: "Social Media",
    role: "Lead",
    registrationNumber: "24BSA10098",
    email: "yash.24bsa@vitbhopal.ac.in",
    phone: "9867330059",
    image: "",
    tags: ["LEAD", "CINEMATOGRAPHY", "MEDIA"],
    bio: "Lead of Social Media at QIC. Driving cinematography, club public presence, and digital media reach.",
    stats: {
      yearsInPractice: 2,
      rating: 4.9,
      projects: 14,
    },
    socials: {
      email: "yash.24bsa@vitbhopal.ac.in",
    },
  },
  {
    id: "sm-2",
    name: "Sujay Dhananjay Sonawane",
    title: "Social Media Co-Lead",
    department: "Social Media",
    role: "Co-Lead",
    registrationNumber: "24BCE10501",
    email: "sonawane.24bce10501@vitbhopal.ac.in",
    phone: "7414910116",
    image: "",
    tags: ["CO-LEAD", "VIDEO EDITING", "POST-PRODUCTION"],
    bio: "Co-Lead of Social Media. Managing video editing, narrative pacing, and engaging club video content.",
    stats: {
      yearsInPractice: 2,
      rating: 4.8,
      projects: 12,
    },
    socials: {
      email: "sonawane.24bce10501@vitbhopal.ac.in",
    },
  },
  {
    id: "sm-3",
    name: "Mohammed Rabbani",
    title: "Core Member (Cinematographer)",
    department: "Social Media",
    role: "Core Member",
    registrationNumber: "24MIM10023",
    email: "mohammed.24mim10023@vitbhopal.ac.in",
    phone: "6302068012",
    image: "",
    tags: ["CORE", "CINEMATOGRAPHER", "MEDIA"],
    bio: "Core Cinematographer capturing dynamic footage, club events, and highlight reels.",
    stats: { yearsInPractice: 1, rating: 4.7, projects: 6 },
    socials: { email: "mohammed.24mim10023@vitbhopal.ac.in" },
  },
  {
    id: "sm-4",
    name: "Shreya Saloni",
    title: "Core Member (Cinematographer)",
    department: "Social Media",
    role: "Core Member",
    registrationNumber: "24BAI10170",
    email: "shrey.24bai10170@vitbhopal.ac.in",
    phone: "9777141539",
    image: "",
    tags: ["CORE", "CINEMATOGRAPHER", "MEDIA"],
    bio: "Core Cinematographer covering major events, campus moments, and video productions.",
    stats: { yearsInPractice: 1, rating: 4.7, projects: 5 },
    socials: { email: "shrey.24bai10170@vitbhopal.ac.in" },
  },
  {
    id: "sm-5",
    name: "Sonal Yadav",
    title: "Core Member (Cinematographer)",
    department: "Social Media",
    role: "Core Member",
    registrationNumber: "24BAI10361",
    email: "sonal.24bai10361@vitbhopal.ac.in",
    phone: "9993853174",
    image: "",
    tags: ["CORE", "CINEMATOGRAPHER", "VISUALS"],
    bio: "Core Cinematographer bringing creative camera angles and vibrant event coverage to life.",
    stats: { yearsInPractice: 1, rating: 4.7, projects: 5 },
    socials: { email: "sonal.24bai10361@vitbhopal.ac.in" },
  },
  {
    id: "sm-6",
    name: "Dilisha Jain",
    title: "Core Member (Cinematographer)",
    department: "Social Media",
    role: "Core Member",
    registrationNumber: "24BCY10056",
    email: "dilisha.24bcy10056@vitbhopal.ac.in",
    phone: "7435052163",
    image: "",
    tags: ["CORE", "CINEMATOGRAPHER", "CAMERA"],
    bio: "Core Cinematographer creating engaging reels, interview footage, and club stories.",
    stats: { yearsInPractice: 1, rating: 4.6, projects: 4 },
    socials: { email: "dilisha.24bcy10056@vitbhopal.ac.in" },
  },
  {
    id: "sm-7",
    name: "Aaranya Rai",
    title: "Core Member (Cinematographer)",
    department: "Social Media",
    role: "Core Member",
    registrationNumber: "24BOE10016",
    email: "aaranya.24boe10016@vitbhopal.ac.in",
    phone: "9430477803",
    image: "",
    tags: ["CORE", "CINEMATOGRAPHER", "CREATIVE"],
    bio: "Core Cinematographer shooting high-energy event highlights and documentary shorts.",
    stats: { yearsInPractice: 1, rating: 4.7, projects: 5 },
    socials: { email: "aaranya.24boe10016@vitbhopal.ac.in" },
  },
  {
    id: "sm-8",
    name: "Anshima",
    title: "Core Member (Editor)",
    department: "Social Media",
    role: "Core Member",
    registrationNumber: "24BAI10360",
    email: "ai10360@vitbhopal.ac.in",
    phone: "8707812755",
    image: "",
    tags: ["CORE", "EDITOR", "MOTION GRAPHICS"],
    bio: "Core Video Editor polishing reels, audio design, and creative motion graphics.",
    stats: { yearsInPractice: 1, rating: 4.7, projects: 6 },
    socials: { email: "ai10360@vitbhopal.ac.in" },
  },
  {
    id: "sm-9",
    name: "Sangeeta Kumari",
    title: "Core Member (Editor)",
    department: "Social Media",
    role: "Core Member",
    registrationNumber: "24BCY10167",
    email: "sangeeta.24bcy10167@vitbhopal.ac.in",
    phone: "6262178148",
    image: "",
    tags: ["CORE", "EDITOR", "POST-PRODUCTION"],
    bio: "Core Video Editor creating engaging social shorts and multimedia edits.",
    stats: { yearsInPractice: 1, rating: 4.6, projects: 5 },
    socials: { email: "sangeeta.24bcy10167@vitbhopal.ac.in" },
  },
  {
    id: "sm-10",
    name: "Chiraag Kumar Rathor",
    title: "Core Member (Editor)",
    department: "Social Media",
    role: "Core Member",
    registrationNumber: "24BCE10724",
    email: "chiraag.24bce10724@vitbhopal.ac.in",
    phone: "7735511742",
    image: "",
    tags: ["CORE", "EDITOR", "EFFECTS"],
    bio: "Core Video Editor crafting smooth transitions, color grading, and social content.",
    stats: { yearsInPractice: 1, rating: 4.7, projects: 6 },
    socials: { email: "chiraag.24bce10724@vitbhopal.ac.in" },
  },
  {
    id: "sm-11",
    name: "Ipsita Mohanty",
    title: "Core Member (Editor)",
    department: "Social Media",
    role: "Core Member",
    registrationNumber: "24BCE10104",
    email: "ipsita.24bce10104@vitbhopal.ac.in",
    phone: "9030024770",
    image: "",
    tags: ["CORE", "EDITOR", "MEDIA"],
    bio: "Core Video Editor delivering sharp cuts, captions, and club promo packages.",
    stats: { yearsInPractice: 1, rating: 4.7, projects: 5 },
    socials: { email: "ipsita.24bce10104@vitbhopal.ac.in" },
  },
  {
    id: "sm-12",
    name: "Yashaswi",
    title: "Core Member (Editor)",
    department: "Social Media",
    role: "Core Member",
    registrationNumber: "25BSA10097",
    email: "yashaswi.25bsa10097@vitbhopal.ac.in",
    phone: "9560947171",
    image: "",
    tags: ["CORE", "EDITOR", "CONTENT CREATION"],
    bio: "Core Video Editor focusing on engaging storytelling and campus buzz videos.",
    stats: { yearsInPractice: 1, rating: 4.6, projects: 4 },
    socials: { email: "yashaswi.25bsa10097@vitbhopal.ac.in" },
  },
  {
    id: "sm-13",
    name: "Govind Mewada",
    title: "Core Member (Editor)",
    department: "Social Media",
    role: "Core Member",
    registrationNumber: "25MIM10005",
    email: "govind.25mim10005@vitbhopal.ac.in",
    phone: "9343147244",
    image: "",
    tags: ["CORE", "EDITOR", "DIGITAL"],
    bio: "Core Video Editor creating event teasers, recap montages, and club stories.",
    stats: { yearsInPractice: 1, rating: 4.7, projects: 5 },
    socials: { email: "govind.25mim10005@vitbhopal.ac.in" },
  },

  // --- FOUNDERS ---
  {
    id: "fnd-1",
    name: "Founder",
    title: "President & Founder",
    department: "Founders",
    role: "Founder",
    image: "",
    tags: ["FOUNDER", "PRESIDENT", "LEADERSHIP"],
    bio: "Position TBA. Guiding vision, ecosystem growth, and strategic partnerships for Quantum Intelligence Club.",
    isPlaceholder: true,
    stats: { yearsInPractice: 3, rating: 5.0, projects: 20 },
  },
  {
    id: "fnd-2",
    name: "Co-Founder",
    title: "Vice President & Co-Founder",
    department: "Founders",
    role: "Founder",
    image: "",
    tags: ["CO-FOUNDER", "VICE PRESIDENT", "STRATEGY"],
    bio: "Position TBA. Co-leading club operations, organizational direction, and community empowerment.",
    isPlaceholder: true,
    stats: { yearsInPractice: 3, rating: 4.9, projects: 18 },
  },

  // --- EVENT MANAGEMENT ---
  {
    id: "em-1",
    name: "Event Lead",
    title: "Event Management Lead",
    department: "Event Management",
    role: "Lead",
    image: "",
    tags: ["LEAD", "OPERATIONS", "EVENTS"],
    bio: "Position Open / TBA. Organizing hackathons, technical workshops, tech talks, and flagship events.",
    isPlaceholder: true,
    stats: { yearsInPractice: 1, rating: 4.8, projects: 8 },
  },
  {
    id: "em-2",
    name: "Event Co-Lead",
    title: "Event Management Co-Lead",
    department: "Event Management",
    role: "Co-Lead",
    image: "",
    tags: ["CO-LEAD", "LOGISTICS", "COORDINATION"],
    bio: "Position Open / TBA. Coordinating venue logistics, schedules, speaker interactions, and attendee flow.",
    isPlaceholder: true,
    stats: { yearsInPractice: 1, rating: 4.7, projects: 6 },
  },
  {
    id: "em-3",
    name: "Event Core Member",
    title: "Event Core Member",
    department: "Event Management",
    role: "Core Member",
    image: "",
    tags: ["CORE", "EXECUTION", "MANAGEMENT"],
    bio: "Position Open / TBA. Executing event operations, volunteer management, and live stage hosting.",
    isPlaceholder: true,
    stats: { yearsInPractice: 1, rating: 4.6, projects: 4 },
  },

  // --- PR TEAM ---
  {
    id: "pr-1",
    name: "PR Lead",
    title: "Public Relations Lead",
    department: "PR Team",
    role: "Lead",
    image: "",
    tags: ["LEAD", "OUTREACH", "PARTNERSHIPS"],
    bio: "Position Open / TBA. Heading club external communications, sponsor outreach, and campus relations.",
    isPlaceholder: true,
    stats: { yearsInPractice: 1, rating: 4.8, projects: 7 },
  },
  {
    id: "pr-2",
    name: "PR Co-Lead",
    title: "Public Relations Co-Lead",
    department: "PR Team",
    role: "Co-Lead",
    image: "",
    tags: ["CO-LEAD", "COMMUNICATION", "NETWORKING"],
    bio: "Position Open / TBA. Managing corporate connections, club representation, and publicity campaigns.",
    isPlaceholder: true,
    stats: { yearsInPractice: 1, rating: 4.7, projects: 5 },
  },
  {
    id: "pr-3",
    name: "PR Core Member",
    title: "PR Core Member",
    department: "PR Team",
    role: "Core Member",
    image: "",
    tags: ["CORE", "PUBLICITY", "CAMPUS OUTREACH"],
    bio: "Position Open / TBA. Supporting campus engagement, announcements, and student networking.",
    isPlaceholder: true,
    stats: { yearsInPractice: 1, rating: 4.6, projects: 4 },
  },

  // --- RESEARCH TEAM ---
  {
    id: "res-1",
    name: "Research Lead",
    title: "Research Team Lead",
    department: "Research Team",
    role: "Lead",
    image: "",
    tags: ["LEAD", "QUANTUM COMPUTING", "AI RESEARCH"],
    bio: "Position Open / TBA. Leading research publications, quantum computing investigations, and state-of-the-art AI studies.",
    isPlaceholder: true,
    stats: { yearsInPractice: 2, rating: 4.9, projects: 10 },
  },
  {
    id: "res-2",
    name: "Research Co-Lead",
    title: "Research Team Co-Lead",
    department: "Research Team",
    role: "Co-Lead",
    image: "",
    tags: ["CO-LEAD", "DATA SCIENCE", "PUBLICATIONS"],
    bio: "Position Open / TBA. Driving collaborative papers, technical explorations, and algorithm benchmarks.",
    isPlaceholder: true,
    stats: { yearsInPractice: 1, rating: 4.8, projects: 7 },
  },
  {
    id: "res-3",
    name: "Research Core Member",
    title: "Research Core Member",
    department: "Research Team",
    role: "Core Member",
    image: "",
    tags: ["CORE", "ANALYSIS", "THEORY"],
    bio: "Position Open / TBA. Conducting deep research, literature reviews, and proof-of-concept experiments.",
    isPlaceholder: true,
    stats: { yearsInPractice: 1, rating: 4.7, projects: 4 },
  },
];
